/**
 * Seed script: Bulk insert blocked COD pincodes into MongoDB
 * Run: node scripts/seedCodBlockedPincodes.js
 *
 * Pincodes sourced from provided pincode list (District / State data).
 * Add more pincodes to the PINCODES array below before running.
 */

require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const mongoose = require('mongoose');
const CodBlockedPincode = require('../models/codBlockedPincode');

// ─── PINCODE LIST ────────────────────────────────────────────────────────────
const PINCODES = [
  // ── SCREENSHOT 1 ──────────────────────────────────────────────────────────
  { pincode: '121102', reason: 'Faridabad, Haryana' },
  { pincode: '201102', reason: 'Ghaziabad, Uttar Pradesh' },
  { pincode: '191111', reason: 'Budgam, Jammu & Kashmir' },
  { pincode: '193101', reason: 'Baramulla, Jammu & Kashmir' },
  { pincode: '193222', reason: 'Kupwara, Jammu & Kashmir' },
  { pincode: '192301', reason: 'Pulwama, Jammu & Kashmir' },
  { pincode: '185131', reason: 'Rajauri, Jammu & Kashmir' },
  { pincode: '203207', reason: 'Gautam Buddha Nagar, Uttar Pradesh' },
  { pincode: '193121', reason: 'Baramulla, Jammu & Kashmir' },
  { pincode: '185101', reason: 'Poonch, Jammu & Kashmir' },
  { pincode: '193502', reason: 'Baramulla, Jammu & Kashmir' },
  { pincode: '193221', reason: 'Kupwara, Jammu & Kashmir' },
  { pincode: '185121', reason: 'Rajauri, Jammu & Kashmir' },
  { pincode: '193224', reason: 'Kupwara, Jammu & Kashmir' },
  { pincode: '345001', reason: 'Jaisalmer, Rajasthan' },
  { pincode: '122107', reason: 'Gurugram, Haryana' },
  { pincode: '500003', reason: 'Hyderabad, Telangana' },
  { pincode: '182202', reason: 'Doda, Jammu & Kashmir' },
  { pincode: '841226', reason: 'Siwan, Bihar' },
  { pincode: '508213', reason: 'Nalgonda, Telangana' },
  { pincode: '486886', reason: 'Sidhi, Madhya Pradesh' },
  { pincode: '803101', reason: 'Nalanda, Bihar' },
  { pincode: '476001', reason: 'Morena, Madhya Pradesh' },
  { pincode: '192201', reason: 'Anantnag, Jammu & Kashmir' },
  { pincode: '302031', reason: 'Jaipur, Rajasthan' },
  { pincode: '193501', reason: 'Baramulla, Jammu & Kashmir' },
  { pincode: '800006', reason: 'Patna, Bihar' },
  { pincode: '193411', reason: 'Budgam, Jammu & Kashmir' },
  { pincode: '185132', reason: 'Rajauri, Jammu & Kashmir' },
  { pincode: '122508', reason: 'Bhiwadi, Haryana' },

  // ── SCREENSHOT 2 ──────────────────────────────────────────────────────────
  { pincode: '193401', reason: 'Srinagar, Jammu & Kashmir' },
  { pincode: '121103', reason: 'Faridabad, Haryana' },
  { pincode: '855107', reason: 'Kishanganj, Bihar' },
  { pincode: '190017', reason: 'Srinagar, Jammu & Kashmir' },
  { pincode: '192121', reason: 'Srinagar, Jammu & Kashmir' },
  { pincode: '121106', reason: 'Faridabad, Haryana' },
  { pincode: '301707', reason: 'Alwar, Rajasthan' },
  { pincode: '303303', reason: 'Dausa, Rajasthan' },
  { pincode: '245304', reason: 'Ghaziabad, Uttar Pradesh' },
  { pincode: '821115', reason: 'Rohtas, Bihar' },
  { pincode: '304001', reason: 'Tonk, Rajasthan' },
  { pincode: '122108', reason: 'Gurugram, Haryana' },
  { pincode: '303108', reason: 'Jaipur, Rajasthan' },
  { pincode: '274304', reason: 'Kushinagar, Uttar Pradesh' },
  { pincode: '474006', reason: 'Gwalior, Madhya Pradesh' },

  // ── SCREENSHOT 3 ──────────────────────────────────────────────────────────
  { pincode: '203205', reason: 'Bulandshahr, Uttar Pradesh' },
  { pincode: '334803', reason: 'Bikaner, Rajasthan' },
  { pincode: '342301', reason: 'Phalodi, Rajasthan' },
  { pincode: '509301', reason: 'Mahabubnagar, Telangana' },
  { pincode: '147101', reason: 'Patiala, Punjab' },
  { pincode: '322201', reason: 'Sawai Madhopur, Rajasthan' },
  { pincode: '505301', reason: 'Karim Nagar, Telangana' },
  { pincode: '855101', reason: 'Kishanganj, Bihar' },
  { pincode: '335804', reason: 'Ganganagar, Rajasthan' },
  { pincode: '185111', reason: 'Poonch, Jammu & Kashmir' },
  { pincode: '314001', reason: 'Dungarpur, Rajasthan' },
  { pincode: '182301', reason: 'Udhampur, Jammu & Kashmir' },
  { pincode: '331023', reason: 'Churu, Rajasthan' },
  { pincode: '193122', reason: 'Baramulla, Jammu & Kashmir' },
  { pincode: '303702', reason: 'Jaipur, Rajasthan' },
  { pincode: '331803', reason: 'Bikaner, Rajasthan' },
  { pincode: '803201', reason: 'Patna, Bihar' },
  { pincode: '321022', reason: 'Bharatpur, Rajasthan' },
  { pincode: '322001', reason: 'Sawai Madhopur, Rajasthan' },
  { pincode: '321024', reason: 'Bharatpur, Rajasthan' },
  { pincode: '272175', reason: 'Sant Kabir Nagar, Uttar Pradesh' },
  { pincode: '851204', reason: 'Khagaria, Bihar' },
  { pincode: '732201', reason: 'Malda, West Bengal' },
  { pincode: '341510', reason: 'Nagaur, Rajasthan' },
  { pincode: '476337', reason: 'Sheopur, Madhya Pradesh' },
  { pincode: '328001', reason: 'Dholpur, Rajasthan' },
  { pincode: '281403', reason: 'Mathura, Uttar Pradesh' },
  { pincode: '303012', reason: 'Jaipur, Rajasthan' },
  { pincode: '783129', reason: 'Goalpara, Assam' },
  { pincode: '122104', reason: 'Gurugram, Haryana' },
  { pincode: '343041', reason: 'Jalor, Rajasthan' },

  // ── SCREENSHOT 4 ──────────────────────────────────────────────────────────
  { pincode: '364290', reason: 'Bhavnagar, Gujarat' },
  { pincode: '122105', reason: 'Gurugram, Haryana' },
  { pincode: '303007', reason: 'Jaipur, Rajasthan' },
  { pincode: '800027', reason: 'Patna, Bihar' },
  { pincode: '192125', reason: 'Anantnag, Jammu & Kashmir' },
  { pincode: '342027', reason: 'Jodhpur, Rajasthan' },
  { pincode: '301411', reason: 'Alwar, Rajasthan' },
  { pincode: '302028', reason: 'Jaipur, Rajasthan' },
  { pincode: '816109', reason: 'Sahibganj, Jharkhand' },
  { pincode: '185212', reason: 'Rajauri, Jammu & Kashmir' },
  { pincode: '303301', reason: 'Jaipur, Rajasthan' },
  { pincode: '486123', reason: 'Rewa, Madhya Pradesh' },
  { pincode: '764036', reason: 'Koraput, Odisha' },
  { pincode: '121101', reason: 'Faridabad, Haryana' },
  { pincode: '203201', reason: 'Gautam Buddha Nagar, Uttar Pradesh' },
  { pincode: '303313', reason: 'Dausa, Rajasthan' },

  // ── SCREENSHOT 5 ──────────────────────────────────────────────────────────
  { pincode: '474003', reason: 'Gwalior, Madhya Pradesh' },
  { pincode: '586128', reason: 'Bijapur, Karnataka' },
  { pincode: '140501', reason: 'Mohali, Punjab' },
  { pincode: '343040', reason: 'Jalor, Rajasthan' },
  { pincode: '732125', reason: 'Malda, West Bengal' },
  { pincode: '782105', reason: 'Marigaon, Assam' },
  { pincode: '303103', reason: 'Jaipur, Rajasthan' },
  { pincode: '835302', reason: 'Lohardaga, Jharkhand' },
  { pincode: '247663', reason: 'Haridwar, Uttarakhand' },
  { pincode: '193301', reason: 'Baramulla, Jammu & Kashmir' },
  { pincode: '193303', reason: 'Baramulla, Jammu & Kashmir' },
  { pincode: '201015', reason: 'Lucknow HQ, Uttar Pradesh' },
  { pincode: '803213', reason: 'Patna, Bihar' },
  { pincode: '192129', reason: 'Anantnag, Jammu & Kashmir' },
  { pincode: '475110', reason: 'Gwalior, Madhya Pradesh' },
  { pincode: '821101', reason: 'Kaimur (Bhabua), Bihar' },
  { pincode: '244102', reason: 'Moradabad, Uttar Pradesh' },
  { pincode: '302027', reason: 'Jaipur, Rajasthan' },
  { pincode: '344704', reason: 'Barmer, Rajasthan' },
  { pincode: '342303', reason: 'Jodhpur, Rajasthan' },
  { pincode: '502325', reason: 'Medak, Telangana' },
  { pincode: '321203', reason: 'Bharatpur, Rajasthan' },
  { pincode: '193225', reason: 'Kupwara, Jammu & Kashmir' },
  { pincode: '283204', reason: 'Firozabad, Uttar Pradesh' },
  { pincode: '825401', reason: 'Chatra, Jharkhand' },
  { pincode: '283125', reason: 'Agra, Uttar Pradesh' },
  { pincode: '335803', reason: 'Hanumangarh, Rajasthan' },
  { pincode: '345021', reason: 'Jaisalmer, Rajasthan' },
  { pincode: '244241', reason: 'Jyotiba Phule Nagar, Uttar Pradesh' },
  { pincode: '250101', reason: 'Bagpat, Uttar Pradesh' },
  { pincode: '362268', reason: 'Junagadh, Gujarat' },
  { pincode: '844102', reason: 'Vaishali, Bihar' },

  // ── SCREENSHOT 6 ──────────────────────────────────────────────────────────
  { pincode: '303503', reason: 'Dausa, Rajasthan' },
  { pincode: '321023', reason: 'Bharatpur, Rajasthan' },
  { pincode: '783135', reason: 'Dhubri, Assam' },
  { pincode: '328021', reason: 'Dholpur, Rajasthan' },
  { pincode: '335707', reason: 'Ganganagar, Rajasthan' },
  { pincode: '247774', reason: 'Muzaffarnagar, Uttar Pradesh' },
  { pincode: '799035', reason: 'West Tripura, Tripura' },
  { pincode: '322241', reason: 'Karauli, Rajasthan' },
  { pincode: '281502', reason: 'Mathura, Uttar Pradesh' },
  { pincode: '461775', reason: 'Hoshangabad, Madhya Pradesh' },
  { pincode: '132107', reason: 'Panipat, Haryana' },
  { pincode: '344031', reason: 'Barmer, Rajasthan' },
  { pincode: '486889', reason: 'Sidhi, Madhya Pradesh' },
  { pincode: '782123', reason: 'Nagaon, Assam' },
  { pincode: '121105', reason: 'Faridabad, Haryana' },

  // ── SCREENSHOT 7 ──────────────────────────────────────────────────────────
  { pincode: '121107', reason: 'Faridabad, Haryana' },
  { pincode: '123021', reason: 'Rewari, Haryana' },
  { pincode: '193103', reason: 'Baramulla, Jammu & Kashmir' },
  { pincode: '247656', reason: 'Haridwar, Uttarakhand' },
  { pincode: '263152', reason: 'Udham Singh Nagar, Uttarakhand' },
  { pincode: '301402', reason: 'Alwar, Rajasthan' },
  { pincode: '301404', reason: 'Alwar, Rajasthan' },
  { pincode: '321205', reason: 'Bharatpur, Rajasthan' },
  { pincode: '332715', reason: 'Sikar, Rajasthan' },
  { pincode: '342037', reason: 'Jodhpur, Rajasthan' },
  { pincode: '501501', reason: 'K.V.Rangareddy, Telangana' },
  { pincode: '123023', reason: 'Rewari, Haryana' },
  { pincode: '422012', reason: 'Nashik, Maharashtra' },
  { pincode: '799103', reason: 'West Tripura, Tripura' },
  { pincode: '335701', reason: 'Ganganagar, Rajasthan' },
  { pincode: '363530', reason: 'Surendra Nagar, Gujarat' },
  { pincode: '799045', reason: 'West Tripura, Tripura' },
  { pincode: '811105', reason: 'Sheikhpura, Bihar' },
  { pincode: '523226', reason: 'Prakasam, Andhra Pradesh' },
  { pincode: '344035', reason: 'Barmer, Rajasthan' },
  { pincode: '585310', reason: 'Gulbarga, Karnataka' },
  { pincode: '334603', reason: 'Bikaner, Rajasthan' },
  { pincode: '193504', reason: 'Baramulla, Jammu & Kashmir' },
  { pincode: '281204', reason: 'Mathura, Uttar Pradesh' },
  { pincode: '304502', reason: 'Tonk, Rajasthan' },
  { pincode: '508248', reason: 'Nalgonda, Telangana' },
  { pincode: '185211', reason: 'Srinagar HQ, Jammu & Kashmir' },
  { pincode: '304021', reason: 'Tonk, Rajasthan' },
  { pincode: '342015', reason: 'Jodhpur, Rajasthan' },
  { pincode: '782445', reason: 'Nagaon, Assam' },
  { pincode: '203202', reason: 'Gautam Buddha Nagar, Uttar Pradesh' },

  // ── SCREENSHOT 8 ──────────────────────────────────────────────────────────
  { pincode: '301405', reason: 'Alwar, Rajasthan' },
  { pincode: '431133', reason: 'Aurangabad, Maharashtra' },
  { pincode: '464551', reason: 'Raisen, Madhya Pradesh' },
  { pincode: '782440', reason: 'Nagaon, Assam' },
  { pincode: '844122', reason: 'Munger, Bihar' },
  { pincode: '244601', reason: 'Moradabad, Uttar Pradesh' },
  { pincode: '284204', reason: 'Jhansi, Uttar Pradesh' },
  { pincode: '821109', reason: 'Kaimur (Bhabua), Bihar' },
  { pincode: '243202', reason: 'Bareilly, Uttar Pradesh' },
  { pincode: '332404', reason: 'Sikar, Rajasthan' },
  { pincode: '516101', reason: 'Cuddapah, Andhra Pradesh' },
  { pincode: '824231', reason: 'Gaya, Bihar' },
  { pincode: '243123', reason: 'Pilibhit, Uttar Pradesh' },
  { pincode: '484774', reason: 'Shahdol, Madhya Pradesh' },
  { pincode: '782124', reason: 'Nagaon, Assam' },

  // ── SCREENSHOT 9 ──────────────────────────────────────────────────────────
  { pincode: '824232', reason: 'Gaya, Bihar' },
  { pincode: '132113', reason: 'Panipat, Haryana' },
  { pincode: '247232', reason: 'Saharanpur, Uttar Pradesh' },
  { pincode: '362225', reason: 'Junagadh, Gujarat' },
  { pincode: '733208', reason: 'North Dinajpur, West Bengal' },
  { pincode: '784115', reason: 'Darrang, Assam' },
  { pincode: '244222', reason: 'Jyotiba Phule Nagar, Uttar Pradesh' },
  { pincode: '244925', reason: 'Rampur, Uttar Pradesh' },
  { pincode: '245205', reason: 'Ghaziabad, Uttar Pradesh' },
  { pincode: '303805', reason: 'Jaipur, Rajasthan' },
  { pincode: '431123', reason: 'Beed, Maharashtra' },
  { pincode: '531055', reason: 'Visakhapatnam, Andhra Pradesh' },
  { pincode: '804452', reason: 'Patna, Bihar' },
  { pincode: '845418', reason: 'East Champaran, Bihar' },
  { pincode: '244301', reason: 'Moradabad, Uttar Pradesh' },
  { pincode: '301028', reason: 'Alwar, Rajasthan' },
  { pincode: '303008', reason: 'Jaipur, Rajasthan' },
  { pincode: '591317', reason: 'Belgaum, Karnataka' },
  { pincode: '453115', reason: 'Indore, Madhya Pradesh' },
  { pincode: '465674', reason: 'Rajgarh, Madhya Pradesh' },
  { pincode: '583277', reason: 'Bellary, Karnataka' },
  { pincode: '843329', reason: 'Sheohar, Bihar' },
  { pincode: '303603', reason: 'Jaipur, Rajasthan' },
  { pincode: '825322', reason: 'Giridh, Jharkhand' },
  { pincode: '182143', reason: 'Doda, Jammu & Kashmir' },
  { pincode: '221011', reason: 'Varanasi, Uttar Pradesh' },
  { pincode: '303338', reason: 'Jaipur, Rajasthan' },
  { pincode: '303712', reason: 'Jaipur, Rajasthan' },
  { pincode: '335704', reason: 'Ganganagar, Rajasthan' },
  { pincode: '412220', reason: 'Pune, Maharashtra' },
  { pincode: '465441', reason: 'Shajapur, Madhya Pradesh' },
  { pincode: '476111', reason: 'Morena, Madhya Pradesh' },

  // ── SCREENSHOT 10 ─────────────────────────────────────────────────────────
  { pincode: '845437', reason: 'East Champaran, Bihar' },
  { pincode: '281306', reason: 'Hathras, Uttar Pradesh' },
  { pincode: '301408', reason: 'Alwar, Rajasthan' },
  { pincode: '783331', reason: 'Dhubri, Assam' },
  { pincode: '803202', reason: 'Patna, Bihar' },
  { pincode: '246734', reason: 'Bijnor, Uttar Pradesh' },
  { pincode: '413701', reason: 'Ahmed Nagar, Maharashtra' },
  { pincode: '829202', reason: 'Latehar, Jharkhand' },
  { pincode: '852122', reason: 'Purnia, Bihar' },
  { pincode: '854202', reason: 'Purnia, Bihar' },
  { pincode: '208023', reason: 'Kanpur Nagar, Uttar Pradesh' },
  { pincode: '303328', reason: 'Jaipur, Rajasthan' },
  { pincode: '313803', reason: 'Udaipur, Rajasthan' },
  { pincode: '454660', reason: 'Dhar, Madhya Pradesh' },
  { pincode: '764073', reason: 'Nabarangapur, Odisha' },

  // ── SCREENSHOT 11 ─────────────────────────────────────────────────────────
  { pincode: '784514', reason: 'Darrang, Assam' },
  { pincode: '824211', reason: 'Gaya, Bihar' },
  { pincode: '202124', reason: 'Aligarh, Uttar Pradesh' },
  { pincode: '788119', reason: 'Cachar, Assam' },
  { pincode: '812006', reason: 'Bhagalpur, Bihar' },
  { pincode: '821108', reason: 'Kaimur (Bhabua), Bihar' },
  { pincode: '845101', reason: 'West Champaran, Bihar' },
  { pincode: '854312', reason: 'Araria, Bihar' },
  { pincode: '127046', reason: 'Bhiwani, Haryana' },
  { pincode: '344032', reason: 'Barmer, Rajasthan' },
  { pincode: '825405', reason: 'Hazaribag, Jharkhand' },
  { pincode: '852128', reason: 'Madhepura, Bihar' },
  { pincode: '182201', reason: 'Doda, Jammu & Kashmir' },
  { pincode: '192210', reason: 'Anantnag, Jammu & Kashmir' },
  { pincode: '533435', reason: 'East Godavari, Andhra Pradesh' },
  { pincode: '585328', reason: 'Bidar, Karnataka' },
  { pincode: '782125', reason: 'Nagaon, Assam' },
  { pincode: '202150', reason: 'Aligarh, Uttar Pradesh' },
  { pincode: '301406', reason: 'Alwar, Rajasthan' },
  { pincode: '303106', reason: 'Jaipur, Rajasthan' },
  { pincode: '825323', reason: 'Hazaribag, Jharkhand' },
  { pincode: '852127', reason: 'Saharsa, Bihar' },
  { pincode: '192305', reason: 'Pulwama, Jammu & Kashmir' },
  { pincode: '203135', reason: 'Gautam Buddha Nagar, Uttar Pradesh' },
  { pincode: '389180', reason: 'Dahod, Gujarat' },
  { pincode: '811308', reason: 'Jamui, Bihar' },
  { pincode: '822110', reason: 'Palamau, Jharkhand' },
  { pincode: '845105', reason: 'West Champaran, Bihar' },
  { pincode: '845412', reason: 'East Champaran, Bihar' },
  { pincode: '261201', reason: 'Sitapur, Uttar Pradesh' },
  { pincode: '342023', reason: 'Jodhpur, Rajasthan' },
  { pincode: '342606', reason: 'Jodhpur, Rajasthan' },

  // ── SCREENSHOT 12 ─────────────────────────────────────────────────────────
  { pincode: '781136', reason: 'Kamrup, Assam' },
  { pincode: '788155', reason: 'Hailakandi, Assam' },
  { pincode: '201302', reason: 'Ghaziabad, Uttar Pradesh' },
  { pincode: '221104', reason: 'Varanasi, Uttar Pradesh' },
  { pincode: '301030', reason: 'Alwar, Rajasthan' },
  { pincode: '303806', reason: 'Jaipur, Rajasthan' },
  { pincode: '591302', reason: 'Belgaum, Karnataka' },
  { pincode: '732206', reason: 'Malda, West Bengal' },
  { pincode: '752011', reason: 'Puri, Odisha' },
  { pincode: '803212', reason: 'Patna, Bihar' },
  { pincode: '848201', reason: 'Begusarai, Bihar' },
  { pincode: '175029', reason: 'Mandi, Himachal Pradesh' },
  { pincode: '250406', reason: 'Meerut, Uttar Pradesh' },
  { pincode: '283110', reason: 'Agra, Uttar Pradesh' },
  { pincode: '301024', reason: 'Alwar, Rajasthan' },

  // ── SCREENSHOT 13 ─────────────────────────────────────────────────────────
  { pincode: '321602', reason: 'Bharatpur, Rajasthan' },
  { pincode: '476229', reason: 'Morena, Madhya Pradesh' },
  { pincode: '811213', reason: 'Munger, Bihar' },
  { pincode: '825408', reason: 'Chatra, Jharkhand' },
  { pincode: '854329', reason: 'Araria, Bihar' },
  { pincode: '301026', reason: 'Alwar, Rajasthan' },
  { pincode: '342307', reason: 'Jodhpur, Rajasthan' },
  { pincode: '490011', reason: 'Durg, Chattisgarh' },
  { pincode: '524345', reason: 'Nellore, Andhra Pradesh' },
  { pincode: '841426', reason: 'Gopalganj, Bihar' },
  { pincode: '844506', reason: 'Vaishali, Bihar' },
  { pincode: '243505', reason: 'Bareilly, Uttar Pradesh' },
  { pincode: '244401', reason: 'Moradabad, Uttar Pradesh' },
  { pincode: '530047', reason: 'Visakhapatnam, Andhra Pradesh' },
  { pincode: '801109', reason: 'Patna, Bihar' },
  { pincode: '845433', reason: 'East Champaran, Bihar' },
  { pincode: '852124', reason: 'Madhepura, Bihar' },
  { pincode: '212107', reason: 'Allahabad, Uttar Pradesh' },
  { pincode: '486331', reason: 'Rewa, Madhya Pradesh' },
  { pincode: '522414', reason: 'Guntur, Andhra Pradesh' },
  { pincode: '733215', reason: 'North Dinajpur, West Bengal' },
  { pincode: '851134', reason: 'Begusarai, Bihar' },
  { pincode: '185202', reason: 'Rajauri, Jammu & Kashmir' },
  { pincode: '192306', reason: 'Pulwama, Jammu & Kashmir' },
  { pincode: '811101', reason: 'Sheikhpura, Bihar' },
  { pincode: '841239', reason: 'Siwan, Bihar' },
  { pincode: '244402', reason: 'Moradabad, Uttar Pradesh' },
  { pincode: '251309', reason: 'Muzaffarnagar, Uttar Pradesh' },
  { pincode: '301022', reason: 'Alwar, Rajasthan' },
  { pincode: '303104', reason: 'Jaipur, Rajasthan' },
  { pincode: '464668', reason: 'Raisen, Madhya Pradesh' },
  { pincode: '782126', reason: 'Marigaon, Assam' },

  // ── SCREENSHOT 14 ─────────────────────────────────────────────────────────
  { pincode: '244251', reason: 'Jyotiba Phule Nagar, Uttar Pradesh' },
  { pincode: '301025', reason: 'Alwar, Rajasthan' },
  { pincode: '331802', reason: 'Churu, Rajasthan' },
  { pincode: '431204', reason: 'Jalna, Maharashtra' },
  { pincode: '783334', reason: 'Dhubri, Assam' },
  { pincode: '845454', reason: 'West Champaran, Bihar' },
  { pincode: '847212', reason: 'Madhubani, Bihar' },
  { pincode: '283202', reason: 'Agra, Uttar Pradesh' },
  { pincode: '303801', reason: 'Jaipur, Rajasthan' },
  { pincode: '303901', reason: 'Jaipur, Rajasthan' },
  { pincode: '325220', reason: 'Baran, Rajasthan' },
  { pincode: '343022', reason: 'Jalor, Rajasthan' },
  { pincode: '382427', reason: 'Ahmedabad, Gujarat' },
  { pincode: '443204', reason: 'Buldhana, Maharashtra' },
  { pincode: '486881', reason: 'Sidhi, Madhya Pradesh' },

  // ── SCREENSHOT 15 ─────────────────────────────────────────────────────────
  { pincode: '843128', reason: 'Muzaffarpur, Bihar' },
  { pincode: '845449', reason: 'West Champaran, Bihar' },
  { pincode: '226401', reason: 'Lucknow, Uttar Pradesh' },
  { pincode: '251318', reason: 'Muzaffarnagar, Uttar Pradesh' },
  { pincode: '303120', reason: 'Jaipur, Rajasthan' },
  { pincode: '303501', reason: 'Dausa, Rajasthan' },
  { pincode: '413216', reason: 'Solapur, Maharashtra' },
  { pincode: '458002', reason: 'Mandsaur, Madhya Pradesh' },
  { pincode: '476224', reason: 'Morena, Madhya Pradesh' },
  { pincode: '572107', reason: 'Tumkur, Karnataka' },
  { pincode: '600120', reason: 'Tiruvallur, Tamil Nadu' },
  { pincode: '822116', reason: 'Palamau, Jharkhand' },
  { pincode: '828116', reason: 'Dhanbad, Jharkhand' },
  { pincode: '845106', reason: 'West Champaran, Bihar' },
  { pincode: '175124', reason: 'Mandi, Himachal Pradesh' },
  { pincode: '192102', reason: 'Anantnag, Jammu & Kashmir' },
  { pincode: '847105', reason: 'Samastipur, Bihar' },
  { pincode: '851205', reason: 'Khagaria, Bihar' },
  { pincode: '203209', reason: 'Gautam Buddha Nagar, Uttar Pradesh' },
  { pincode: '281406', reason: 'Mathura, Uttar Pradesh' },
  { pincode: '307022', reason: 'Sirohi, Rajasthan' },
  { pincode: '783339', reason: 'Dhubri, Assam' },
  { pincode: '843109', reason: 'Muzaffarpur, Bihar' },
  { pincode: '854104', reason: 'Katihar, Bihar' },
  { pincode: '192304', reason: 'Pulwama, Jammu & Kashmir' },
  { pincode: '305023', reason: 'Ajmer, Rajasthan' },
  { pincode: '341509', reason: 'Nagaur, Rajasthan' },
  { pincode: '781308', reason: 'Barpeta, Assam' },
  { pincode: '799104', reason: 'South Tripura, Tripura' },
  { pincode: '813213', reason: 'Bhagalpur, Bihar' },
  { pincode: '822124', reason: 'Garhwa, Jharkhand' },

  // ── SCREENSHOT 16 ─────────────────────────────────────────────────────────
  { pincode: '845301', reason: 'East Champaran, Bihar' },
  { pincode: '192302', reason: 'Pulwama, Jammu & Kashmir' },
  { pincode: '209101', reason: 'Unnao, Uttar Pradesh' },
  { pincode: '221311', reason: 'Varanasi, Uttar Pradesh' },
  { pincode: '283105', reason: 'Agra, Uttar Pradesh' },
  { pincode: '412411', reason: 'Pune, Maharashtra' },
  { pincode: '431105', reason: 'Jalna, Maharashtra' },
  { pincode: '534198', reason: 'West Godavari, Andhra Pradesh' },
  { pincode: '732207', reason: 'Malda, West Bengal' },
  { pincode: '843313', reason: 'Sitamarhi, Bihar' },
  { pincode: '203203', reason: 'Gautam Buddha Nagar, Uttar Pradesh' },
  { pincode: '221304', reason: 'Sant Ravidas Nagar, Uttar Pradesh' },
  { pincode: '233227', reason: 'Ghazipur, Uttar Pradesh' },
  { pincode: '244242', reason: 'Jyotiba Phule Nagar, Uttar Pradesh' },
  { pincode: '563133', reason: 'Kolar, Karnataka' },
  { pincode: '801110', reason: 'Patna, Bihar' },

  // ── SCREENSHOT 17 ─────────────────────────────────────────────────────────
  { pincode: '852219', reason: 'Muzaffarpur, Bihar' },
  { pincode: '125076', reason: 'Sirsa, Haryana' },
  { pincode: '231208', reason: 'Sonbhadra, Uttar Pradesh' },
  { pincode: '321608', reason: 'Dausa, Rajasthan' },
  { pincode: '332402', reason: 'Sikar, Rajasthan' },
  { pincode: '332602', reason: 'Sikar, Rajasthan' },
  { pincode: '342802', reason: 'Jodhpur, Rajasthan' },
  { pincode: '431705', reason: 'Hingoli, Maharashtra' },
  { pincode: '733210', reason: 'North Dinajpur, West Bengal' },
  { pincode: '787054', reason: 'Lakhimpur, Assam' },
  { pincode: '825406', reason: 'Hazaribag, Jharkhand' },
  { pincode: '851214', reason: 'Khagaria, Bihar' },
  { pincode: '221303', reason: 'Sant Ravidas Nagar, Uttar Pradesh' },
  { pincode: '327022', reason: 'Banswara, Rajasthan' },
  { pincode: '344033', reason: 'Barmer, Rajasthan' },
  { pincode: '422303', reason: 'Nashik, Maharashtra' },
  { pincode: '444503', reason: 'Akola, Maharashtra' },
  { pincode: '732103', reason: 'Malda, West Bengal' },
  { pincode: '782485', reason: 'Karbi Anglong, Assam' },
  { pincode: '788734', reason: 'Hailakandi, Assam' },
  { pincode: '815316', reason: 'Giridh, Jharkhand' },
  { pincode: '829144', reason: 'Hazaribag, Jharkhand' },
  { pincode: '841227', reason: 'Siwan, Bihar' },
  { pincode: '852221', reason: 'Saharsa, Bihar' },
  { pincode: '133004', reason: 'Ambala, Haryana' },
  { pincode: '205264', reason: 'Mainpuri, Uttar Pradesh' },
  { pincode: '206245', reason: 'Etawah, Uttar Pradesh' },
  { pincode: '243720', reason: 'Bareilly, Uttar Pradesh' },
  { pincode: '283102', reason: 'Agra, Uttar Pradesh' },
  { pincode: '303005', reason: 'Jaipur, Rajasthan' },
  { pincode: '413104', reason: 'Pune, Maharashtra' },

  // ── SCREENSHOT 18 ─────────────────────────────────────────────────────────
  { pincode: '465661', reason: 'Rajgarh, Madhya Pradesh' },
  { pincode: '476115', reason: 'Morena, Madhya Pradesh' },
  { pincode: '476444', reason: 'Morena, Madhya Pradesh' },
  { pincode: '480441', reason: 'Chhindwara, Madhya Pradesh' },
  { pincode: '483220', reason: 'Katni, Madhya Pradesh' },
  { pincode: '486882', reason: 'Sidhi, Madhya Pradesh' },
  { pincode: '591311', reason: 'Belgaum, Karnataka' },
  { pincode: '755018', reason: 'Jajapur, Odisha' },
  { pincode: '825320', reason: 'Giridh, Jharkhand' },
  { pincode: '844114', reason: 'Vaishali, Bihar' },
  { pincode: '845426', reason: 'East Champaran, Bihar' },
  { pincode: '124108', reason: 'Jhajjar, Haryana' },
  { pincode: '182203', reason: 'Doda, Jammu & Kashmir' },
  { pincode: '202138', reason: 'Aligarh, Uttar Pradesh' },
  { pincode: '324004', reason: 'Kota, Rajasthan' },
  { pincode: '501508', reason: 'K.V.Rangareddy, Telangana' },

  // ── SCREENSHOT 19 ─────────────────────────────────────────────────────────
  { pincode: '781127', reason: 'Kamrup, Assam' },
  { pincode: '835219', reason: 'Ranchi, Jharkhand' },
  { pincode: '841238', reason: 'Siwan, Bihar' },
  { pincode: '212303', reason: 'Allahabad, Uttar Pradesh' },
  { pincode: '273201', reason: 'Gorakhpur, Uttar Pradesh' },
  { pincode: '303903', reason: 'Jaipur, Rajasthan' },
  { pincode: '305802', reason: 'Ajmer, Rajasthan' },
  { pincode: '342305', reason: 'Jodhpur, Rajasthan' },
  { pincode: '431107', reason: 'Aurangabad, Maharashtra' },
  { pincode: '484334', reason: 'Anuppur, Madhya Pradesh' },
  { pincode: '484771', reason: 'Shahdol, Madhya Pradesh' },
  { pincode: '563128', reason: 'Kolar, Karnataka' },
  { pincode: '591213', reason: 'Belgaum, Karnataka' },
  { pincode: '754029', reason: 'Cuttack, Odisha' },
  { pincode: '788723', reason: 'Karimganj, Assam' },
  { pincode: '801108', reason: 'Patna, Bihar' },
  { pincode: '843119', reason: 'Muzaffarpur, Bihar' },
  { pincode: '848203', reason: 'Khagaria, Bihar' },
  { pincode: '209202', reason: 'Kanpur Dehat, Uttar Pradesh' },
  { pincode: '212201', reason: 'Kaushambi, Uttar Pradesh' },
  { pincode: '212655', reason: 'Fatehpur, Uttar Pradesh' },
  { pincode: '221507', reason: 'Allahabad, Uttar Pradesh' },
  { pincode: '303505', reason: 'Dausa, Rajasthan' },
  { pincode: '332718', reason: 'Sikar, Rajasthan' },
  { pincode: '385320', reason: 'Banaskantha, Gujarat' },
  { pincode: '401102', reason: 'Thane, Maharashtra' },
  { pincode: '444403', reason: 'Washim, Maharashtra' },
  { pincode: '517588', reason: 'Chittoor, Andhra Pradesh' },
  { pincode: '782481', reason: 'Nagaon, Assam' },
  { pincode: '805103', reason: 'Nawada, Bihar' },
];
// ─────────────────────────────────────────────────────────────────────────────

async function seed() {
  await mongoose.connect(process.env.DATABASE);
  console.log('✅ Connected to MongoDB');

  let upserted = 0, errors = 0;

  for (const entry of PINCODES) {
    try {
      await CodBlockedPincode.updateOne(
        { pincode: entry.pincode },
        {
          $set: { reason: entry.reason },
          $setOnInsert: {
            type: 'exact',
            blockLevel: 'partial-cod',
            advanceAmount: null,
            isActive: true
          }
        },
        { upsert: true }
      );
      upserted++;
    } catch (err) {
      console.error(`❌ Error for ${entry.pincode}:`, err.message);
      errors++;
    }
  }

  const total = await CodBlockedPincode.countDocuments({ blockLevel: 'partial-cod' });
  console.log(`\n📊 Done — Upserted: ${upserted} | Errors: ${errors} | Total partial-cod in DB: ${total}`);
  await mongoose.disconnect();
}

seed().catch(err => {
  console.error('Fatal error:', err);
  process.exit(1);
});
